name: Deploy to SSH Server

on:
  workflow_call:

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Create .env config file
        run: cp example.env .env

      - name: Build website
        run: npm run build
      
      - name: Copy files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: marco-lenschau.de
          username: github
          key: ${{ secrets.SECRET_KEY }}
          port: 22
          source: "./build/*"
          target: "/var/www/html/docs/"