name: Deploy to SSH Server

on:
  workflow_call:

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          # cache: npm

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Create .env config file
        run: cp example.env .env

      - name: Build website
        run: npm run build && cp -r build app

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: app

  deploy:
    name: Deploy via SSH
    needs: build
    if: ${{ github.ref_name == github.event.repository.default_branch }}

    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          path: app

      - name: Copy files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: marco-lenschau.de
          username: github
          key: ${{ secrets.SECRET_KEY }}
          port: 22
          source: "./"
          target: "/var/www/html/docs/"
          